remote_theme: pages-themes/slate@v0.2.0
#remote_theme: pmarsceill/just-the-docs
plugins:
- jekyll-remote-theme 
title: KumPelNet
description: Kumpulan Pelajaran di Internet
github: [metadata]
page_excerpts: true