remote_theme: samarsault/texture
plugins:
- jekyll-remote-theme 
- jekyll-tidy
github: [metadata]
page_excerpts: true
texture:
  title: Ihsan Praditya
  tagline: Dokumentasi
  date_format: "%d %-b, %Y"
  style: green

exclude: ['images', 'files', 'vendor']
