# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem "github-pages", group: :jekyll_plugins

gem "jekyll"

# gem "jekyll-feed"

# gem "just-the-docs"

gem "jekyll-tidy", "~> 0.2.2"

# gem "rails"

gem "texture"

gem "webrick", "~> 1.7"
